import * as pulumi from "@pulumi/pulumi";
import {
	type CustomResourceOptions,
	dynamic,
	type Output,
} from "@pulumi/pulumi";
import * as random from "@pulumi/random";
import type { LiteLLMApiKeyArgs, LiteLLMTeamArgs } from "./config-types.ts";

/**
 * Resource options accepted by sector7 dynamic resources.
 *
 * Pulumi dynamic resources are executed by the Node.js dynamic provider runtime,
 * not by a cloud provider plugin. Passing `provider` or `providers` makes Pulumi
 * route the resource through the wrong provider bridge, which fails with a
 * misleading `pulumi-nodejs:dynamic:Resource` unknown-token error.
 */
export type DynamicResourceOptions = Omit<
	CustomResourceOptions,
	"provider" | "providers"
>;

// ---------------------------------------------------------------------------
// Resolved provider input/state shapes
//
// Pulumi resolves every `Input<T>` before invoking the dynamic provider, so the
// callbacks below see plain JSON values only. Optional fields are normalized to
// sentinel empty values ("" / [] / {}) by the wrapping component so the provider
// never has to reason about `undefined`.
// ---------------------------------------------------------------------------

/** Coordinates + credentials for reaching the LiteLLM admin API. */
interface AdminTarget {
	proxyNamespace: string;
	masterKey: string;
	proxyDeploymentName: string;
	proxyPort: number;
}

interface TeamProviderInputs extends AdminTarget {
	teamAlias: string;
	/** Caller-requested team_id; "" lets LiteLLM assign one. */
	desiredTeamId: string;
	models: string[];
	/** "" when unset. */
	maxBudget: number | "";
	budgetDuration: string;
	tags: string[];
	metadata: Record<string, string>;
}

interface TeamProviderState extends TeamProviderInputs {
	/** The team_id actually in LiteLLM (resolved on create/adopt). */
	teamId: string;
}

interface KeyProviderInputs extends AdminTarget {
	keyAlias: string;
	/** The `sk-...` value, generated by a RandomPassword outside the provider. */
	keyValue: string;
	models: string[];
	teamId: string;
	userId: string;
	budgetId: string;
	maxBudget: number | "";
	budgetDuration: string;
	duration: string;
	aliases: Record<string, string>;
	tags: string[];
	metadata: Record<string, string>;
}

interface KeyProviderState extends KeyProviderInputs {
	/** The LiteLLM token hash returned by /key/generate. */
	tokenId: string;
}

// ---------------------------------------------------------------------------
// Runtime helpers (port-forward transport + admin API client)
//
// Every Node/k8s import is performed via dynamic `import()` *inside* these
// functions. Pulumi serializes the provider object via V8 source capture; a
// top-level ES import of a native/third-party module captures native-code
// functions that cannot be serialized ("Function code: function () { [native
// code] }"). Dynamic import() is emitted verbatim and evaluated at runtime
// after deserialization. Same constraint the R2 dynamic provider documents.
// https://www.pulumi.com/docs/concepts/resources/dynamic-providers/#how-dynamic-providers-are-serialized
// ---------------------------------------------------------------------------

/**
 * Open a short-lived port-forward to a ready pod of the LiteLLM proxy
 * deployment, invoke `fn` with a `http://127.0.0.1:<port>` base URL, then tear
 * the forward down. This mirrors the reachability model of the previous
 * `kubectl exec` approach (works wherever kube credentials work, no tailnet
 * dependency) while running entirely in-process.
 */
async function withProxyBaseUrl<T>(
	target: AdminTarget,
	fn: (baseUrl: string) => Promise<T>,
): Promise<T> {
	const k8s = await import("@kubernetes/client-node");
	const net = await import("node:net");

	const kc = new k8s.KubeConfig();
	kc.loadFromDefault();

	const apps = kc.makeApiClient(k8s.AppsV1Api);
	const core = kc.makeApiClient(k8s.CoreV1Api);

	// Resolve the deployment's pod selector, then pick a ready pod. Reading the
	// selector at runtime avoids hardcoding the proxy's label scheme and works
	// for any deployment name the caller passes.
	const depResp = await apps.readNamespacedDeployment({
		name: target.proxyDeploymentName,
		namespace: target.proxyNamespace,
	});
	// client-node 1.x returns the body directly; tolerate the 0.x {body} shape.
	// biome-ignore lint/suspicious/noExplicitAny: k8s client response is loosely typed across majors
	const dep: any = (depResp as any)?.body ?? depResp;
	const matchLabels: Record<string, string> =
		dep?.spec?.selector?.matchLabels ?? {};
	const labelSelector = Object.entries(matchLabels)
		.map(([k, v]) => `${k}=${v}`)
		.join(",");
	if (!labelSelector) {
		throw new Error(
			`deployment ${target.proxyNamespace}/${target.proxyDeploymentName} has no spec.selector.matchLabels`,
		);
	}

	const podResp = await core.listNamespacedPod({
		namespace: target.proxyNamespace,
		labelSelector,
	});
	// biome-ignore lint/suspicious/noExplicitAny: k8s client response is loosely typed across majors
	const pods: any[] = ((podResp as any)?.body ?? podResp)?.items ?? [];
	const ready =
		pods.find(
			// biome-ignore lint/suspicious/noExplicitAny: pod object is loosely typed
			(p: any) =>
				p?.status?.phase === "Running" &&
				(p?.status?.conditions ?? []).some(
					// biome-ignore lint/suspicious/noExplicitAny: condition object is loosely typed
					(c: any) => c?.type === "Ready" && c?.status === "True",
				),
		) ?? pods[0];
	const podName: string | undefined = ready?.metadata?.name;
	if (!podName) {
		throw new Error(
			`no running pod found for deployment ${target.proxyNamespace}/${target.proxyDeploymentName}`,
		);
	}

	const forward = new k8s.PortForward(kc);
	const server = net.createServer((socket) => {
		forward
			.portForward(
				target.proxyNamespace,
				podName,
				[target.proxyPort],
				socket,
				null,
				socket,
			)
			.catch((err: unknown) =>
				socket.destroy(err instanceof Error ? err : new Error(String(err))),
			);
	});

	await new Promise<void>((resolve, reject) => {
		server.once("error", reject);
		server.listen(0, "127.0.0.1", () => resolve());
	});

	const address = server.address();
	const localPort =
		address && typeof address === "object" ? address.port : undefined;
	if (!localPort) {
		await new Promise<void>((resolve) => server.close(() => resolve()));
		throw new Error("failed to bind a local port for the LiteLLM port-forward");
	}

	try {
		return await fn(`http://127.0.0.1:${localPort}`);
	} finally {
		await new Promise<void>((resolve) => server.close(() => resolve()));
	}
}

/** Issue an authenticated request against the LiteLLM admin API. */
async function adminRequest(
	baseUrl: string,
	masterKey: string,
	path: string,
	method: "GET" | "POST",
	body?: unknown,
	// biome-ignore lint/suspicious/noExplicitAny: admin API responses are dynamic JSON
): Promise<any> {
	const response = await fetch(`${baseUrl}${path}`, {
		method,
		headers: {
			Authorization: `Bearer ${masterKey}`,
			...(body !== undefined ? { "Content-Type": "application/json" } : {}),
		},
		body: body !== undefined ? JSON.stringify(body) : undefined,
	});

	const text = await response.text();
	if (!response.ok) {
		throw new Error(
			`LiteLLM ${method} ${path} failed: ${response.status} ${response.statusText}\n${text}`,
		);
	}
	if (!text) return {};

	// biome-ignore lint/suspicious/noExplicitAny: admin API responses are dynamic JSON
	let parsed: any;
	try {
		parsed = JSON.parse(text);
	} catch {
		return text;
	}
	if (parsed && typeof parsed === "object" && parsed.error) {
		throw new Error(
			`LiteLLM ${method} ${path} returned an error: ${JSON.stringify(parsed.error)}`,
		);
	}
	return parsed;
}

/**
 * Find an existing team to adopt, matched by explicit `team_id` only.
 *
 * Adoption is deliberately NOT done by `team_alias`: aliases are not unique on a
 * LiteLLM admin plane, so matching one would let a new resource adopt and
 * overwrite an unrelated team's models/budgets/metadata — an authorization
 * boundary problem on a shared control plane. A team created without an explicit
 * `team_id` has no stable identity to re-find, so it is always created fresh
 * (callers that need idempotent adoption must pass a stable `team_id`).
 */
async function findTeamId(
	baseUrl: string,
	masterKey: string,
	desiredTeamId: string,
): Promise<string | undefined> {
	if (!desiredTeamId) return undefined;
	const data = await adminRequest(baseUrl, masterKey, "/team/list", "GET");
	// biome-ignore lint/suspicious/noExplicitAny: team list shape varies by LiteLLM version
	const teams: any[] = Array.isArray(data)
		? data
		: (data?.teams ?? data?.data ?? []);
	for (const team of teams) {
		if (!team || typeof team !== "object") continue;
		if (team.team_id === desiredTeamId) return team.team_id;
	}
	return undefined;
}

/**
 * Find an existing key by alias, returning its token hash.
 *
 * LiteLLM `/key/info` never exposes the `sk-...` value, only the hash — so this
 * is used solely to detect a pre-existing key during adoption/recreation, not
 * to recover the secret.
 *
 * The match is scoped to BOTH `alias` and `teamId`: aliases are not globally
 * unique in LiteLLM, so matching on alias alone would let `create()` delete a
 * same-named key belonging to a different team (or a manually-managed key) on a
 * shared admin plane. Requiring the team to match confines deletion to keys
 * this resource actually owns.
 */
async function findKeyHashByAlias(
	baseUrl: string,
	masterKey: string,
	alias: string,
	teamId: string,
): Promise<string | undefined> {
	const data = await adminRequest(baseUrl, masterKey, "/key/list", "GET");
	// biome-ignore lint/suspicious/noExplicitAny: key list shape varies by LiteLLM version
	const rawKeys: any[] = Array.isArray(data)
		? data
		: (data?.keys ?? data?.data ?? []);
	const hashes: string[] = rawKeys
		// biome-ignore lint/suspicious/noExplicitAny: key entry may be a string or object
		.map((k: any) => (typeof k === "string" ? k : (k?.token ?? k?.key_name)))
		.filter((h: unknown): h is string => typeof h === "string" && h.length > 0);
	if (hashes.length === 0) return undefined;

	const infos = await Promise.all(
		hashes.map(async (hash) => {
			try {
				const info = await adminRequest(
					baseUrl,
					masterKey,
					`/key/info?key=${encodeURIComponent(hash)}`,
					"GET",
				);
				return { hash, info: info?.info ?? info };
			} catch {
				return { hash, info: undefined };
			}
		}),
	);
	for (const { hash, info } of infos) {
		if (
			info &&
			typeof info === "object" &&
			info.key_alias === alias &&
			(info.team_id ?? "") === (teamId ?? "")
		) {
			return hash;
		}
	}
	return undefined;
}

/**
 * True when any admin-connection field changed. Such a change does not alter
 * the remote team/key, but it must still flow into stored state so a later
 * update/delete targets the new deployment and uses the new master key rather
 * than the stale ones — so diff() treats it as an in-place change.
 */
function adminTargetChanged(olds: AdminTarget, news: AdminTarget): boolean {
	return (
		olds.proxyNamespace !== news.proxyNamespace ||
		olds.proxyDeploymentName !== news.proxyDeploymentName ||
		olds.proxyPort !== news.proxyPort ||
		olds.masterKey !== news.masterKey
	);
}

/** Stable JSON for order-insensitive comparison in diff(). */
function stableJson(value: unknown): string {
	if (Array.isArray(value)) {
		return JSON.stringify([...value].map(stableValue).sort());
	}
	return JSON.stringify(stableValue(value));
}

function stableValue(value: unknown): unknown {
	if (Array.isArray(value)) return value.map(stableValue);
	if (value && typeof value === "object") {
		const obj = value as Record<string, unknown>;
		return Object.keys(obj)
			.sort()
			.reduce<Record<string, unknown>>((acc, key) => {
				acc[key] = stableValue(obj[key]);
				return acc;
			}, {});
	}
	return value;
}

/**
 * LiteLLM's `/team/update` and `/key/update` treat an *omitted* field as "leave
 * unchanged", so the create/generate bodies that simply skip empty optionals
 * cannot clear a value that was previously set. When a field transitions from
 * set (olds) to empty (news), send an explicit reset (`null` / `[]`) so the
 * change actually propagates instead of silently persisting remotely while
 * Pulumi records the empty state. Shared by the team and key update paths.
 */
function applyClearedFields(
	body: Record<string, unknown>,
	olds: { maxBudget?: number | ""; budgetDuration?: string; tags?: string[] },
	news: { maxBudget: number | ""; budgetDuration: string; tags: string[] },
): void {
	if (
		olds.maxBudget !== "" &&
		olds.maxBudget !== undefined &&
		news.maxBudget === ""
	) {
		body.max_budget = null;
	}
	if (olds.budgetDuration && !news.budgetDuration) body.budget_duration = null;
	if ((olds.tags?.length ?? 0) > 0 && news.tags.length === 0) body.tags = [];
}

// ---------------------------------------------------------------------------
// Team — request bodies + provider
// ---------------------------------------------------------------------------

function buildTeamBody(
	inputs: TeamProviderInputs,
	teamIdOverride?: string,
): Record<string, unknown> {
	const body: Record<string, unknown> = {
		team_alias: inputs.teamAlias,
		models: inputs.models,
		metadata: inputs.metadata,
	};
	// tags is a LiteLLM Enterprise feature — only send it when non-empty.
	if (inputs.tags.length > 0) body.tags = inputs.tags;
	const teamId = teamIdOverride || inputs.desiredTeamId;
	if (teamId) body.team_id = teamId;
	if (inputs.maxBudget !== "") body.max_budget = inputs.maxBudget;
	if (inputs.budgetDuration) body.budget_duration = inputs.budgetDuration;
	return body;
}

/** Team /team/update body that also clears fields removed since the last apply. */
function buildTeamUpdateBody(
	olds: TeamProviderState,
	news: TeamProviderInputs,
	teamId: string,
): Record<string, unknown> {
	const body = buildTeamBody(news, teamId);
	applyClearedFields(body, olds, news);
	return body;
}

const teamProvider: dynamic.ResourceProvider = {
	async check(
		_olds: TeamProviderState,
		news: TeamProviderInputs,
	): Promise<dynamic.CheckResult> {
		const failures: dynamic.CheckFailure[] = [];
		for (const property of [
			"proxyNamespace",
			"masterKey",
			"proxyDeploymentName",
			"teamAlias",
		] as const) {
			if (!news[property]) {
				failures.push({ property, reason: `${property} is required` });
			}
		}
		return { inputs: news, failures };
	},

	async diff(
		_id: string,
		olds: TeamProviderState,
		news: TeamProviderInputs,
	): Promise<dynamic.DiffResult> {
		const replaces: string[] = [];
		// A different explicit team_id is a different team — replace. (Empty desired
		// id means "let LiteLLM keep the assigned one"; not a replacement trigger.)
		if (news.desiredTeamId && olds.desiredTeamId !== news.desiredTeamId) {
			replaces.push("desiredTeamId");
		}
		const changed =
			replaces.length > 0 ||
			adminTargetChanged(olds, news) ||
			stableJson(olds.models) !== stableJson(news.models) ||
			olds.teamAlias !== news.teamAlias ||
			(olds.maxBudget ?? "") !== (news.maxBudget ?? "") ||
			(olds.budgetDuration ?? "") !== (news.budgetDuration ?? "") ||
			stableJson(olds.tags ?? []) !== stableJson(news.tags ?? []) ||
			stableJson(olds.metadata ?? {}) !== stableJson(news.metadata ?? {});
		return { changes: changed, replaces, deleteBeforeReplace: false };
	},

	async create(inputs: TeamProviderInputs): Promise<dynamic.CreateResult> {
		return withProxyBaseUrl(inputs, async (baseUrl) => {
			const existing = await findTeamId(
				baseUrl,
				inputs.masterKey,
				inputs.desiredTeamId,
			);
			let teamId = existing;
			if (teamId) {
				// Adopt a pre-existing team (idempotent create) and reconcile its
				// settings to the desired state in the same step.
				await adminRequest(
					baseUrl,
					inputs.masterKey,
					"/team/update",
					"POST",
					buildTeamBody(inputs, teamId),
				);
			} else {
				const resp = await adminRequest(
					baseUrl,
					inputs.masterKey,
					"/team/new",
					"POST",
					buildTeamBody(inputs),
				);
				teamId = resp?.team_id ?? inputs.desiredTeamId;
			}
			if (!teamId) {
				throw new Error("LiteLLM /team/new returned no team_id");
			}
			return { id: teamId, outs: { ...inputs, teamId } };
		});
	},

	async update(
		id: string,
		olds: TeamProviderState,
		news: TeamProviderInputs,
	): Promise<dynamic.UpdateResult> {
		return withProxyBaseUrl(news, async (baseUrl) => {
			await adminRequest(
				baseUrl,
				news.masterKey,
				"/team/update",
				"POST",
				buildTeamUpdateBody(olds, news, id),
			);
			return { outs: { ...news, teamId: id } };
		});
	},

	async delete(id: string, props: TeamProviderState): Promise<void> {
		if (!id) return;
		await withProxyBaseUrl(props, async (baseUrl) => {
			await adminRequest(baseUrl, props.masterKey, "/team/delete", "POST", {
				team_ids: [id],
			});
		});
	},
};

// ---------------------------------------------------------------------------
// Key — request bodies + provider
// ---------------------------------------------------------------------------

function buildKeyGenerateBody(
	inputs: KeyProviderInputs,
): Record<string, unknown> {
	const body: Record<string, unknown> = {
		key_alias: inputs.keyAlias,
		key: inputs.keyValue,
		models: inputs.models,
		aliases: inputs.aliases,
		metadata: inputs.metadata,
	};
	if (inputs.tags.length > 0) body.tags = inputs.tags;
	if (inputs.teamId) body.team_id = inputs.teamId;
	if (inputs.userId) body.user_id = inputs.userId;
	if (inputs.budgetId) body.budget_id = inputs.budgetId;
	if (inputs.maxBudget !== "") body.max_budget = inputs.maxBudget;
	if (inputs.budgetDuration) body.budget_duration = inputs.budgetDuration;
	if (inputs.duration) body.duration = inputs.duration;
	return body;
}

function buildKeyUpdateBody(
	olds: KeyProviderState,
	news: KeyProviderInputs,
): Record<string, unknown> {
	// /key/update is keyed on the token value (LiteLLM hashes it server-side).
	// team_id / key value changes are handled by replacement, not update.
	const body: Record<string, unknown> = {
		key: news.keyValue,
		key_alias: news.keyAlias,
		models: news.models,
		aliases: news.aliases,
		metadata: news.metadata,
	};
	if (news.tags.length > 0) body.tags = news.tags;
	if (news.userId) body.user_id = news.userId;
	if (news.budgetId) body.budget_id = news.budgetId;
	if (news.maxBudget !== "") body.max_budget = news.maxBudget;
	if (news.budgetDuration) body.budget_duration = news.budgetDuration;
	if (news.duration) body.duration = news.duration;
	// Clear fields removed since the last apply (omission would leave them set).
	applyClearedFields(body, olds, news);
	if (olds.duration && !news.duration) body.duration = null;
	return body;
}

const keyProvider: dynamic.ResourceProvider = {
	async check(
		_olds: KeyProviderState,
		news: KeyProviderInputs,
	): Promise<dynamic.CheckResult> {
		const failures: dynamic.CheckFailure[] = [];
		for (const property of [
			"proxyNamespace",
			"masterKey",
			"proxyDeploymentName",
			"keyAlias",
			"keyValue",
		] as const) {
			if (!news[property]) {
				failures.push({ property, reason: `${property} is required` });
			}
		}
		return { inputs: news, failures };
	},

	async diff(
		_id: string,
		olds: KeyProviderState,
		news: KeyProviderInputs,
	): Promise<dynamic.DiffResult> {
		const replaces: string[] = [];
		// Rotating the secret or moving teams means a new key in LiteLLM.
		if (olds.keyValue !== news.keyValue) replaces.push("keyValue");
		if ((olds.teamId ?? "") !== (news.teamId ?? "")) replaces.push("teamId");
		const changed =
			replaces.length > 0 ||
			adminTargetChanged(olds, news) ||
			(olds.keyAlias ?? "") !== (news.keyAlias ?? "") ||
			stableJson(olds.models) !== stableJson(news.models) ||
			stableJson(olds.aliases ?? {}) !== stableJson(news.aliases ?? {}) ||
			stableJson(olds.metadata ?? {}) !== stableJson(news.metadata ?? {}) ||
			stableJson(olds.tags ?? []) !== stableJson(news.tags ?? []) ||
			(olds.userId ?? "") !== (news.userId ?? "") ||
			(olds.budgetId ?? "") !== (news.budgetId ?? "") ||
			(olds.maxBudget ?? "") !== (news.maxBudget ?? "") ||
			(olds.budgetDuration ?? "") !== (news.budgetDuration ?? "") ||
			(olds.duration ?? "") !== (news.duration ?? "");
		return { changes: changed, replaces, deleteBeforeReplace: true };
	},

	async create(inputs: KeyProviderInputs): Promise<dynamic.CreateResult> {
		return withProxyBaseUrl(inputs, async (baseUrl) => {
			// Idempotency: LiteLLM /key/info can't return the original sk-... value,
			// so a pre-existing key with this alias can't be adopted in place. Delete
			// it and recreate with our known (RandomPassword-derived) key value.
			const existingHash = await findKeyHashByAlias(
				baseUrl,
				inputs.masterKey,
				inputs.keyAlias,
				inputs.teamId,
			);
			if (existingHash) {
				await adminRequest(baseUrl, inputs.masterKey, "/key/delete", "POST", {
					keys: [existingHash],
				});
			}
			const resp = await adminRequest(
				baseUrl,
				inputs.masterKey,
				"/key/generate",
				"POST",
				buildKeyGenerateBody(inputs),
			);
			const tokenId: string = resp?.token ?? resp?.token_id ?? "";
			// Never fall back to the sk-... value: Pulumi resource IDs are stored
			// in plaintext in state, so using the secret as the ID would leak the
			// credential (and delete expects a LiteLLM token hash, not the secret).
			if (!tokenId) {
				throw new Error("LiteLLM /key/generate returned no token id");
			}
			return {
				id: tokenId,
				outs: { ...inputs, tokenId },
			};
		});
	},

	async update(
		id: string,
		olds: KeyProviderState,
		news: KeyProviderInputs,
	): Promise<dynamic.UpdateResult> {
		return withProxyBaseUrl(news, async (baseUrl) => {
			await adminRequest(
				baseUrl,
				news.masterKey,
				"/key/update",
				"POST",
				buildKeyUpdateBody(olds, news),
			);
			return { outs: { ...news, tokenId: olds.tokenId || id } };
		});
	},

	async delete(id: string, props: KeyProviderState): Promise<void> {
		const token = id || props.tokenId;
		if (!token) return;
		await withProxyBaseUrl(props, async (baseUrl) => {
			await adminRequest(baseUrl, props.masterKey, "/key/delete", "POST", {
				keys: [token],
			});
		});
	},
};

// ---------------------------------------------------------------------------
// Public dynamic resources
// ---------------------------------------------------------------------------

/** Build the normalized, fully-resolved provider inputs for a team. */
function teamProviderInputs(args: LiteLLMTeamArgs) {
	return {
		proxyNamespace: args.proxyNamespace,
		masterKey: args.masterKey,
		proxyDeploymentName: pulumi.output(args.proxyDeploymentName ?? "litellm"),
		proxyPort: pulumi.output(args.proxyPort ?? 4000),
		teamAlias: args.teamAlias,
		desiredTeamId: pulumi.output(args.teamId ?? ""),
		models: pulumi.output(args.models ?? []),
		maxBudget: pulumi
			.output(args.maxBudget)
			.apply((value) => (value === undefined ? "" : value)),
		budgetDuration: pulumi.output(args.budgetDuration ?? ""),
		tags: pulumi.output(args.tags ?? []),
		metadata: pulumi.output(args.metadata ?? {}),
	};
}

class LiteLLMTeamRecord extends dynamic.Resource {
	public readonly teamId!: Output<string>;

	constructor(
		name: string,
		args: ReturnType<typeof teamProviderInputs>,
		opts?: DynamicResourceOptions,
	) {
		super(teamProvider, name, { teamId: undefined, ...args }, opts);
	}
}

/**
 * A LiteLLM team, managed as a first-class Pulumi resource.
 *
 * Unlike the previous `command.local.Command` implementation, this reconciles
 * drift: changing `models`, `maxBudget`, `budgetDuration`, `teamAlias`, `tags`,
 * or `metadata` calls LiteLLM `/team/update` on the next `pulumi up`. Only a
 * change to an explicit `teamId` triggers a replacement.
 *
 * Transport: the provider opens a short-lived port-forward to a ready pod of
 * the proxy deployment and calls the admin API over `localhost` — the same
 * reachability model as the old `kubectl exec` script, with no tailnet
 * dependency.
 */
export class LiteLLMTeam extends pulumi.ComponentResource {
	public readonly teamId: pulumi.Output<string>;

	constructor(
		name: string,
		args: LiteLLMTeamArgs,
		opts?: pulumi.ComponentResourceOptions,
	) {
		super("sector7:litellm:Team", name, args, opts);

		const record = new LiteLLMTeamRecord(
			`${name}-team`,
			teamProviderInputs(args),
			{ parent: this },
		);

		this.teamId = record.teamId;
		this.registerOutputs({ teamId: this.teamId });
	}
}

/** Build the normalized, fully-resolved provider inputs for a key. */
function keyProviderInputs(
	args: LiteLLMApiKeyArgs,
	keyValue: pulumi.Output<string>,
) {
	return {
		proxyNamespace: args.proxyNamespace,
		masterKey: args.masterKey,
		proxyDeploymentName: pulumi.output(args.proxyDeploymentName ?? "litellm"),
		proxyPort: pulumi.output(args.proxyPort ?? 4000),
		keyAlias: args.keyAlias,
		keyValue,
		models: pulumi.output(args.models ?? []),
		teamId: pulumi.output(args.teamId ?? ""),
		userId: pulumi.output(args.userId ?? ""),
		budgetId: pulumi.output(args.budgetId ?? ""),
		maxBudget: pulumi
			.output(args.maxBudget)
			.apply((value) => (value === undefined ? "" : value)),
		budgetDuration: pulumi.output(args.budgetDuration ?? ""),
		duration: pulumi.output(args.duration ?? ""),
		aliases: pulumi.output(args.aliases ?? {}),
		tags: pulumi.output(args.tags ?? []),
		metadata: pulumi.output(args.metadata ?? {}),
	};
}

class LiteLLMApiKeyRecord extends dynamic.Resource {
	public readonly tokenId!: Output<string>;

	constructor(
		name: string,
		args: ReturnType<typeof keyProviderInputs>,
		opts?: DynamicResourceOptions,
	) {
		super(keyProvider, name, { tokenId: undefined, ...args }, opts);
	}
}

/**
 * A LiteLLM virtual key, managed as a first-class Pulumi resource.
 *
 * The `sk-...` value is derived from a `RandomPassword` named `${name}-secret`
 * (unchanged from the previous implementation, so existing keys keep their
 * value). Changing `models`, `aliases`, `metadata`, `tags`, budget, or
 * `duration` calls LiteLLM `/key/update` on the next `pulumi up`; rotating the
 * key value or moving teams triggers a replacement.
 */
export class LiteLLMApiKey extends pulumi.ComponentResource {
	public readonly key: pulumi.Output<string>;
	public readonly tokenId: pulumi.Output<string>;

	constructor(
		name: string,
		args: LiteLLMApiKeyArgs,
		opts?: pulumi.ComponentResourceOptions,
	) {
		super("sector7:litellm:ApiKey", name, args, opts);

		const keySecret = new random.RandomPassword(
			`${name}-secret`,
			{
				length: 29,
				special: false,
			},
			{ parent: this },
		);
		const actualKey = pulumi.interpolate`sk-${keySecret.result}`;

		const record = new LiteLLMApiKeyRecord(
			`${name}-key`,
			keyProviderInputs(args, actualKey),
			{ parent: this, additionalSecretOutputs: ["keyValue", "tokenId"] },
		);

		this.key = pulumi.secret(actualKey);
		this.tokenId = pulumi.secret(record.tokenId);

		this.registerOutputs({
			key: this.key,
			tokenId: this.tokenId,
		});
	}
}
