/**
 * Worker script template for uptime monitoring with D1 storage for both probe
 * results and failure-streak alert state, plus webhook alerting on
 * failure-state transitions.
 *
 * ADR-020: Cloudflare Worker Uptime Monitor
 * ADR-030: Move alert state from KV to D1 (removes the KV dependency)
 */

/**
 * Configuration for a single monitored endpoint.
 */
export interface MonitorTarget {
	/**
	 * Unique identifier for this monitor (alphanumeric, dashes).
	 * Used as monitor_id in D1 (both probe_results and monitor_state tables).
	 */
	id: string;
	/** Full URL to probe (e.g., "https://grafana.example.com/healthz"). */
	url: string;
	/**
	 * HTTP method. @default "GET"
	 */
	method?: "GET" | "HEAD";
	/**
	 * Expected HTTP status codes. Probe is "ok" if status is in this list.
	 * @default [200]
	 */
	expectedCodes?: number[];
	/**
	 * Maximum response time in milliseconds before marking as failed.
	 * 0 = no timeout enforcement (Worker fetch timeout still applies).
	 * @default 0
	 */
	timeoutMs?: number;
	/**
	 * Substring to search for in the response body.
	 * If set, the probe is "ok" only when the body contains this string.
	 * Only applies to GET requests (HEAD has no body).
	 */
	expectedBody?: string;
	/**
	 * Request headers to send with the probe.
	 */
	headers?: Record<string, string>;
}

/**
 * Generate the Worker script code for uptime monitoring.
 *
 * The generated script:
 * 1. Probes each configured endpoint (fetch with timing).
 * 2. Inserts a row into D1 for each probe result.
 * 3. Reads/writes failure streak state from the D1 monitor_state table.
 * 4. Fires webhook alerts on state transitions (healthy -> unhealthy or vice versa).
 *
 * Alert logic:
 * - A monitor transitions to "unhealthy" after ALERT_THRESHOLD consecutive failures.
 * - A monitor transitions back to "healthy" after RECOVERY_THRESHOLD consecutive successes.
 * - Webhook fires only on state transitions, not on every probe.
 */
export function generateMonitorScript(
	monitors: MonitorTarget[],
	options: {
		enableReadApi?: boolean;
		/** Auth config — reserved for ADR-028 follow-up (full JWT validation). */
		readApiAuth?: { type: "service-token" };
	} = {},
): string {
	const monitorsJson = JSON.stringify(
		monitors.map((m) => ({
			id: m.id,
			url: m.url,
			method: m.method ?? "GET",
			expectedCodes: m.expectedCodes ?? [200],
			timeoutMs: m.timeoutMs ?? 0,
			expectedBody: m.expectedBody ?? null,
			headers: m.headers ?? null,
		})),
		undefined,
		"\t",
	);

	// Build the fetch handler block — only included when enableReadApi is true.
	// This is a placeholder: real D1 aggregation queries and full Service Token
	// validation are follow-up work (per ADR-028).
	const fetchHandler = options.enableReadApi
		? `
	async fetch(request, env) {
		const url = new URL(request.url);
		if (url.pathname === "/stats") {
			const clientId = request.headers.get("CF-Access-Client-Id");
			if (!clientId) {
				return new Response("Unauthorized", { status: 401 });
			}
			return handleStats(env, request);
		}
		return new Response("Not found", { status: 404 });
	},`
		: "";

	// handleStats stub — returns a placeholder response.
	// Full D1 query aggregation to be implemented in follow-up.
	const handleStatsFn = options.enableReadApi
		? `
async function handleStats(env, request) {
	return new Response(JSON.stringify({
		status: "ok",
		message: "Stats endpoint placeholder — D1 queries pending (ADR-028 follow-up)",
		generated_at: new Date().toISOString(),
	}), {
		headers: { "Content-Type": "application/json" },
	});
}
`
		: "";

	return `
/**
 * UptimeMonitor - Synthetic HTTP probe with D1 storage and webhook alerting
 * Generated by @jmmaloney4/sector7 UptimeMonitor component
 * ADR-020: Cloudflare Worker Uptime Monitor
 */

const MONITORS = ${monitorsJson};

const ALERT_THRESHOLD = 3;
const RECOVERY_THRESHOLD = 1;

export default {${fetchHandler}
	async scheduled(controller, env, ctx) {
		const results = [];

		for (const monitor of MONITORS) {
			const result = await probe(monitor, env);
			results.push(result);
		}

		// Insert all results into D1 in a single batch
		if (results.length > 0) {
			const placeholders = results.map(() => "(?, ?, ?, ?, ?, ?, ?, ?)").join(", ");
			const values = results.flatMap((r) => [
				r.ts,
				r.monitor_id,
				r.url,
				r.ok ? 1 : 0,
				r.status,
				r.latency_ms,
				r.error ?? null,
				r.region_hint ?? null,
			]);

			await env.DB.prepare(
				\`INSERT INTO probe_results (ts, monitor_id, url, ok, status, latency_ms, error, region_hint) VALUES \${placeholders}\`
			)
				.bind(...values)
				.run();
		}

		// Check alert conditions using D1 state. Batched into one SELECT plus one
		// db.batch() UPSERT so the whole run costs exactly 2 D1 queries regardless
		// of monitor count, staying well under D1's 50-queries/invocation free-tier
		// limit (a per-monitor SELECT+UPSERT would fail past ~24 monitors).
		await checkAndAlertBatch(results, env, ctx);
	},
};

async function probe(monitor, env) {
	const start = Date.now();
	const ts = new Date().toISOString();
	let ok = false;
	let status = 0;
	let latencyMs = 0;
	let error = null;

	try {
		const controller = new AbortController();
		const timeout = monitor.timeoutMs > 0 ? setTimeout(() => controller.abort(), monitor.timeoutMs) : undefined;

		const headers = new Headers(monitor.headers ?? {});
		const response = await fetch(monitor.url, {
			method: monitor.method,
			headers,
			signal: controller.signal,
			redirect: "follow",
		});

		if (timeout) clearTimeout(timeout);

		status = response.status;
		latencyMs = Date.now() - start;
		ok = monitor.expectedCodes.includes(status);

		// Check body content if specified and method is GET
		if (ok && monitor.expectedBody && monitor.method === "GET") {
			const text = await response.text();
			ok = text.includes(monitor.expectedBody);
		}
	} catch (e) {
		latencyMs = Date.now() - start;
		error = e instanceof Error ? e.message : String(e);
	}

	return {
		ts,
		monitor_id: monitor.id,
		url: monitor.url,
		ok,
		status,
		latency_ms: latencyMs,
		error,
		region_hint: env.REGION_HINT ?? null,
	};
}

async function checkAndAlertBatch(results, env, ctx) {
	if (results.length === 0) return;

	// 1. Read all monitor states in a single SELECT (1 D1 query). Bound params
	// are capped at 100/statement, so this supports up to 100 monitors per run.
	const ids = results.map((r) => r.monitor_id);
	const stateById = new Map();
	try {
		const placeholders = ids.map(() => "?").join(", ");
		const rows = await env.DB.prepare(
			"SELECT monitor_id, consecutive_failures, consecutive_successes, last_status, last_ts FROM monitor_state WHERE monitor_id IN (" + placeholders + ")"
		)
			.bind(...ids)
			.all();
		for (const row of (rows.results ?? [])) {
			stateById.set(row.monitor_id, row);
		}
	} catch (e) {
		// On a transient read error, do NOT fall back to default "healthy"
		// states: doing so would clear active failure streaks and overwrite the
		// real rows on the UPSERT below, silently dropping alerts. Skip this run
		// and leave the persisted rows untouched.
		console.error("Failed to read monitor state:", e);
		return;
	}

	// 2. Compute the updated state for each monitor and collect the UPSERT
	// statements plus any pending webhook alerts.
	const upsertSql =
		"INSERT INTO monitor_state (monitor_id, consecutive_failures, consecutive_successes, last_status, last_ts, updated_at)" +
		" VALUES (?, ?, ?, ?, ?, ?)" +
		" ON CONFLICT(monitor_id) DO UPDATE SET" +
		"   consecutive_failures = excluded.consecutive_failures," +
		"   consecutive_successes = excluded.consecutive_successes," +
		"   last_status = excluded.last_status," +
		"   last_ts = excluded.last_ts," +
		"   updated_at = excluded.updated_at";

	const writes = [];
	const alerts = [];

	for (const result of results) {
		const state = stateById.get(result.monitor_id) ?? {
			consecutive_failures: 0,
			consecutive_successes: 0,
			last_status: "healthy",
			last_ts: null,
		};

		if (result.ok) {
			state.consecutive_failures = 0;
			state.consecutive_successes++;
		} else {
			state.consecutive_failures++;
			state.consecutive_successes = 0;
		}

		const previousStatus = state.last_status;

		// Only transition healthy -> unhealthy after ALERT_THRESHOLD failures,
		// and unhealthy -> healthy after RECOVERY_THRESHOLD successes.
		if (previousStatus === "healthy" && state.consecutive_failures >= ALERT_THRESHOLD) {
			state.last_status = "unhealthy";
		} else if (previousStatus === "unhealthy" && state.consecutive_successes >= RECOVERY_THRESHOLD) {
			state.last_status = "healthy";
		}
		state.last_ts = result.ts;

		writes.push(
			env.DB.prepare(upsertSql).bind(
				result.monitor_id,
				state.consecutive_failures,
				state.consecutive_successes,
				state.last_status,
				state.last_ts,
				result.ts,
			)
		);

		if (previousStatus !== state.last_status) {
			alerts.push({ result, previousStatus, state });
		}
	}

	// 3. Persist all updated state in one db.batch() (1 D1 query) BEFORE firing
	// any webhook. If the write fails we skip alerting so a dropped write can't
	// re-fire the same alert on the next run.
	try {
		await env.DB.batch(writes);
	} catch (e) {
		console.error("Failed to write monitor state:", e);
		return;
	}

	// 4. Fire webhooks for transitions, now that state is durably persisted.
	for (const { result, previousStatus, state } of alerts) {
		if (state.last_status === "healthy") {
			ctx.waitUntil(sendWebhook(env, {
				type: "recovery",
				monitor_id: result.monitor_id,
				url: result.url,
				ts: result.ts,
				previous_status: previousStatus,
				current_status: state.last_status,
				consecutive_successes: state.consecutive_successes,
				message: \`Monitor \${result.monitor_id} recovered after \${state.consecutive_successes} consecutive successes\`,
			}));
		} else {
			ctx.waitUntil(sendWebhook(env, {
				type: "alert",
				monitor_id: result.monitor_id,
				url: result.url,
				ts: result.ts,
				previous_status: previousStatus,
				current_status: state.last_status,
				consecutive_failures: state.consecutive_failures,
				error: result.error,
				status: result.status,
				message: \`Monitor \${result.monitor_id} is unhealthy (\${state.consecutive_failures} consecutive failures)\`,
			}));
		}
	}
}

async function sendWebhook(env, payload) {
	const webhookUrl = env.WEBHOOK_URL;
	if (!webhookUrl) return;

	try {
		await fetch(webhookUrl, {
			method: "POST",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(payload),
		});
	} catch (e) {
		console.error("Failed to send webhook:", e);
	}
}
${handleStatsFn}`.trim();
}
