name: '📦 pnpm (dogfood)'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*'
permissions:
  contents: write
  packages: write
jobs:
  pnpm:
    uses: jmmaloney4/sector7/.github/workflows/pnpm.yml@854c70baf2ecbf108215f8056f766c6aac4084a0 # main
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.ref }}
      dry_run: ${{ !startsWith(github.ref, 'refs/tags/v') }}
      target: release
